# Generated by Django 6.0.1 on 2026-01-28 07:04

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('objects', authentication.models.OwnerManager()),
            ],
        ),
    ]
