# Generated by Django 6.0.1 on 2026-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storesettings_alter_invoiceitem_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='inventory_i_created_b50583_idx',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
    ]
