# Generated by Django 6.0.1 on 2026-01-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shopprofile_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied to this item', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage applicable to this item', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
