# Generated by Django 6.0.1 on 2026-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_invoiceitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='discount_percentage',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='gst_percentage',
            new_name='gst_percent',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to entire invoice', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST applied to entire invoice', max_digits=5),
        ),
        migrations.AddField(
            model_name='producttype',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN code for this product type', max_length=20),
        ),
    ]
