# Generated by Django 6.0.1 on 2026-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_discount_percentage_invoiceitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stock level for this product. Alert triggered when total quantity falls below this. Default is 10 units.'),
        ),
    ]
