# Generated by Django 6.0.1 on 2026-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_min_stock_level_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_dl_number',
            field=models.CharField(blank=True, help_text='Customer Drug License Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='dl_number',
            field=models.CharField(blank=True, help_text='Drug License Number', max_length=100, null=True),
        ),
    ]
