# Generated by Django 6.0.1 on 2026-01-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_invoice_customer_dl_number_shopprofile_dl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Purchase bill number (assigned by user or system)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date of purchase', null=True),
        ),
    ]
