# Generated by Django 6.0.1 on 2026-01-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchasebill_bill_number_purchasebill_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_return',
            field=models.BooleanField(default=False, help_text='Mark this item as a return (inventory will be increased)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='return_reason',
            field=models.CharField(blank=True, help_text='Reason for return (e.g., Defective, Expired, Customer Request)', max_length=255),
        ),
    ]
