# Generated by Django 6.0.1 on 2026-01-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_invoiceitem_is_return_invoiceitem_return_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('hsn_code', models.CharField(help_text='Unique HSN code (e.g., 3004, 3003)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, help_text="Description of HSN code (e.g., 'Medicaments - Antibiotics')", max_length=255)),
                ('gst_rate', models.DecimalField(decimal_places=2, help_text='GST rate (%) for this HSN code (e.g., 5, 12, 18)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this HSN code is active for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hsn_code'],
                'indexes': [models.Index(fields=['hsn_code'], name='inventory_h_hsn_cod_653951_idx'), models.Index(fields=['gst_rate'], name='inventory_h_gst_rat_a32a19_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.ForeignKey(blank=True, help_text='HSN code for this product (used for GST classification)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.hsn'),
        ),
    ]
